window.WEDDING_CONFIG = {
    groom: "test",
    bride: "new",
    date: "Monday, May 18th",
    time: "5:45 pm AM",
    timeLabel: "Wedding",
    timeSubtext: "",
    timerTarget: "2026-05-18T17:45",
    venue: "prathipati gardens, chilakaluripeet.",
    venueSubtext: "",
    venueUrl: "https://maps.google.com/maps?q=prathipati%20gardens%2C%20chilakaluripeet.&t=&z=15&ie=UTF8&iwloc=&output=embed",
    venueNavigateUrl: "https://www.google.com/maps/search/?q=prathipati%20gardens%2C%20chilakaluripeet.",
    youtubeId: "M5Y7oHJtxhM",
    restreamerUrl: "https://media.eventcast.pro/memfs/test-new-wedding.m3u8",
    restreamerPlayer: "https://media.eventcast.pro/ui/player.html?query=memfs/test-new-wedding.m3u8",
    invitationVideo: "",
    invitationVideos: [],
    thumbnail: "https://res.cloudinary.com/dm1y2iuxm/image/upload/w_1280,h_720,c_fill/co_rgb:7D5A50,e_shadow:40,l_text:Georgia_75_bold:test/g_center,y_-110,fl_layer_apply/co_rgb:7D5A50,e_shadow:30,l_text:Times_60:%2526/g_center,y_-40,fl_layer_apply/co_rgb:7D5A50,e_shadow:40,l_text:Georgia_75_bold:new/g_center,y_30,fl_layer_apply/co_rgb:8E7F7F,e_shadow:20,l_text:Arial_55:Wedding%20Live/g_center,y_140,fl_layer_apply/f_auto,q_auto/base_thumbnails/base_thumbnails/b421a3bc-10fb-4968-87d3-fc7e5902b55a.jpg",
    gallery: [],
    supabaseUrl: "https://lteogzqeuuoxlekhofow.supabase.co",
    supabaseKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0ZW9nenFldXVveGxla2hvZm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTc0ODIsImV4cCI6MjA5Mjc3MzQ4Mn0.eaGIKI5O17PI-bh52IiDDpPr4vqlBOU1Bq_NuAkYZXE",
    eventId: "169156d2-3bb0-436b-97f6-46e89fe9ce3e",
    eventType: "Wedding",
    introText: "",
    photographer: null,
    customInitials: "T & N",
    hideLoaderPhoto: false,
    loaderPhotoUrl: ""
};