window.WEDDING_CONFIG = {
    groom: "Bhargavaram Chowdary",
    bride: "Sasiram Chowdary",
    date: "Saturday, June 27th",
    time: "10:00 AM",
    timeLabel: "Dhoti Ceremony",
    timeSubtext: "Lunch Follows",
    timerTarget: "2026-06-27T10:00:00",
    venue: "JB Garden, Dharanikota, Amaravathi.",
    venueSubtext: "",
    venueNavigateUrl: "https://maps.app.goo.gl/KX2uKJwadV17tgPi7",
    restreamerUrl: "https://media.eventcast.pro/memfs/bhargavaram-sasiram-chowdary-dhoti-ceremony.m3u8",
    restreamerPlayer: "https://media.eventcast.pro/ui/player.html?query=memfs/bhargavaram-sasiram-chowdary-dhoti-ceremony.m3u8",
    youtubeId: "xWoir_5jP7w",
    invitationVideo: "https://pub-fa013cc979d8410e9d307bd2c9e6ecf2.r2.dev/events/bhargavaram-sasiram-chowdary-dhoti-ceremony/invitation.mp4",
    invitationVideos: ["https://pub-fa013cc979d8410e9d307bd2c9e6ecf2.r2.dev/events/bhargavaram-sasiram-chowdary-dhoti-ceremony/invitation.mp4"],
    thumbnail: "https://pub-fa013cc979d8410e9d307bd2c9e6ecf2.r2.dev/thumbnails/bhargavaram-sasiram-chowdary-dhoti-ceremony/seo_thumbnail.png",
    gallery: [],
    supabaseUrl: "https://lteogzqeuuoxlekhofow.supabase.co",
    supabaseKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0ZW9nenFldXVveGxla2hvZm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTc0ODIsImV4cCI6MjA5Mjc3MzQ4Mn0.eaGIKI5O17PI-bh52IiDDpPr4vqlBOU1Bq_NuAkYZXE",
    eventId: "bhargavaram-sasiram-chowdary-dhoti-ceremony",
    eventType: "Dhoti Ceremony",
    introText: "",
    seoTitle: "Bhargavaram Chowdary & Sasiram Chowdary | Dhoti Ceremony Live",
    seoDescription: "Join us live and be part of this special traditional celebration filled with joy, family blessings, and cultural significance.",
    photographer: {"id":"047ebcde-a1e2-4485-b40b-7ec1ddd2078c","name":"Ashok","phone_number":"9010111092","studio_name":"Wedding Studios1","city":"Guntur","created_at":"2026-04-26T18:41:03.827108+00:00","instagram_url":"https://www.instagram.com/wedding_studios1","phone":null,"logo_url":"https://pub-fa013cc979d8410e9d307bd2c9e6ecf2.r2.dev/events/bhargavaram-sasiram-chowdary-dhoti-ceremony/ashok_logo.png","nickname":"Ashok GNT"},
    customInitials: "B & S",
    hideLoaderPhoto: false,
    loaderPhotoUrl: ""
};
