window.WEDDING_CONFIG = {
    groom: "test groom",
    bride: "test bride",
    date: "Wednesday, May 13th",
    time: "11:00 PM",
    timeLabel: "Wedding",
    timeSubtext: "",
    timerTarget: "2026-05-13T23:00",
    venue: "venue, location.",
    venueSubtext: "",
    venueUrl: "https://maps.google.com/maps?q=prathipati%20gardens%2C%20chilakaluripet.&t=&z=15&ie=UTF8&iwloc=&output=embed",
    venueNavigateUrl: "https://www.google.com/maps/search/?q=prathipati%20gardens%2C%20chilakaluripet.",
    youtubeId: "YPvNQbSRj_A",
    restreamerUrl: "",
    restreamerPlayer: "",
    invitationVideo: "",
    invitationVideos: [],
    thumbnail: "https://res.cloudinary.com/df5b4aq7h/image/upload/w_1280,h_720,c_fill/co_rgb:7D5A50,e_shadow:40,l_text:Georgia_75_bold:test%20groom/g_center,y_-110,fl_layer_apply/co_rgb:7D5A50,e_shadow:30,l_text:Times_60:%2526/g_center,y_-40,fl_layer_apply/co_rgb:7D5A50,e_shadow:40,l_text:Georgia_75_bold:test%20bride/g_center,y_30,fl_layer_apply/co_rgb:8E7F7F,e_shadow:20,l_text:Arial_55:Wedding%20Live/g_center,y_140,fl_layer_apply/f_auto,q_auto/base_thumbnails/base_thumbnails/b421a3bc-10fb-4968-87d3-fc7e5902b55a.jpg",
    gallery: [],
    supabaseUrl: "https://lteogzqeuuoxlekhofow.supabase.co",
    supabaseKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0ZW9nenFldXVveGxla2hvZm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTc0ODIsImV4cCI6MjA5Mjc3MzQ4Mn0.eaGIKI5O17PI-bh52IiDDpPr4vqlBOU1Bq_NuAkYZXE",
    eventId: "dac79cbe-7835-4f9e-949d-a2e83d532065",
    eventType: "Wedding",
    introText: "",
    photographer: null,
    customInitials: "T & T",
    hideLoaderPhoto: false,
    loaderPhotoUrl: ""
};