window.WEDDING_CONFIG = {
    groom: "Sravani",
    bride: "Manoj",
    customInitials: "S & M",
    date: "Thursday, June 25",
    time: "07:34 AM",
    timeSubtext: "",
    timerTarget: "2026-06-25T06:30:00",
    venue: "Swagruha Funtion Hall",
    venueSubtext: "Guntur.",
    venueMapLink: "https://maps.app.goo.gl/45AQGeqo83r5jxvb7",
    restreamerUrl: "https://media.eventcast.pro/memfs/sravani-manoj-engagement.m3u8",
    restreamerPlayer: "https://media.eventcast.pro/memfs/sravani-manoj-engagement.m3u8",
    youtubeId: "LvYyM9zM25A",
    invitationVideo: "https://pub-fa013cc979d8410e9d307bd2c9e6ecf2.r2.dev/events/sravani-manoj-engagement/invitation.mp4",
    thumbnail: "https://pub-fa013cc979d8410e9d307bd2c9e6ecf2.r2.dev/thumbnails/sravani-manoj-engagement/seo_thumbnail.jpg",
    gallery: [],
    supabaseUrl: 'https://ntjqjmuripwexwlhfrny.supabase.co',
    supabaseKey: 'sb_publishable_vi_vz9qfKMJnEymw3WaPpg_2A6SeSWR',
    eventId: 'sravani-manoj-engagement'
};
