window.WEDDING_CONFIG = {
    groom: "undefined",
    bride: "Family",
    date: "undefined",
    time: "undefined",
    timeSubtext: "",
    timerTarget: "undefinedT09:00",
    venue: "undefined",
    venueSubtext: "",
    youtubeId: "",
    invitationVideo: "undefined",
    thumbnail: "undefined",
    gallery: [],
    supabaseUrl: "https://lteogzqeuuoxlekhofow.supabase.co",
    supabaseKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0ZW9nenFldXVveGxla2hvZm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTc0ODIsImV4cCI6MjA5Mjc3MzQ4Mn0.eaGIKI5O17PI-bh52IiDDpPr4vqlBOU1Bq_NuAkYZXE",
    eventId: "undefined",
    eventType: "undefined",
    introText: "",
    photographer: null
};